# SPDX-License-Identifier: Apache-2.0

manifest:
  version: "0.13"

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/Dexter9532

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis_6
          - hal_st
          - hal_stm32

  self:
    path: seven-clicker-sample
